#!/bin/bash
#PBS -N autoint
#PBS -o autoint_output_$PBS_JOBID.log
#PBS -e autoint_error_$PBS_JOBID.log
#PBS -l ngpus=1

#PBS -q gpu
#PBS -M rudhresh_manoharan1@baylor.edu
#PBS -m abe

# Load the correct Conda version
export PATH=/home/manoharanr/miniconda3/bin:$PATH

# Activate your Conda environment
source activate env1

# Change to job submission directory
cd /home/manoharanr/glitch/autoint

# Run the Python script
python3 autoint.py