#!/bin/bash
#PBS -N tabnet
#PBS -o tabnet_output_$PBS_JOBID.log
#PBS -e tabnet_error_$PBS_JOBID.log
#PBS -l ngpus=1

#PBS -q gpu
#PBS -M rudhresh_manoharan1@baylor.edu
#PBS -m abe

# Load the correct Conda version
export PATH=/home/manoharanr/anaconda3/bin:$PATH

# Activate your Conda environment
source activate env1

# Change to job submission directory
cd /home/manoharanr/glitch/tabnet

# Run the Python script
python3 tabnet.py